env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: nz2MCGMHwxeP3i2GBlkHuNF65YdYphqotm47lP/7UUnaKuvNIU2rdRyp1dSYs7PbDqJhAiZN7+oGLH51TY2PmA4F+9XTMTY7jQQZIR1upOYwrd5j23PQiyQI8DT9gTIvcmfa1b+fLvs1Oewn8pLAzKnnc8X5y5IZt+aVE+lF2ok=
  - secure: cLe+i3aU08yY+vXlpv0eVE9pf8IM1+1vfJJryb9yi+/T+6cXSYZ3kYNvL8X2ZjKjoUf8zTOZUL7svT/enVFnG7yinbXt8SmY5clBRx+SyNCOUnSc5rmAMmnQw1W6ezI5Yq5qlHn4dd+ShX9xaeHDoDMo25XGfRJIaGlNy9XXuBE=
  - secure: O1BMs4ne8ZTW/Cfp0fJ5/RFIjcEAKja/1N8/861dnF2oYqyuqSbECOgWRmmWQJVCFksDnIejtFbtR6WZM6v/ziKucX2kvqyj5YY/ndfL8BT2CavRGRYwt08pZpkmlCf0y6GGYcjQqUIhEuKvEMqc2eODcQeDxluZPf8tHN2mdhU=
  - secure: soQLcUQsihc6IHwguc+XUJ9biIOAP13oGkrYaiCH5jqvcfv0XsMUaMczBaVw851YdhEDvRK7sJtdt/KlI/X7YhTLgIXmy4EHD2IjHPtoaNAWp2phKp5AgYqQIAQ8t1BzTiFJgZJKBtHV7tE4TjK2HcLVB4pJ/pqYFWd8PwZzmo8=
  - secure: NikH+RDLR7IaOekx0k9A9zrwKKrXwx5k7kovXCKWR4vB6xuD7iZSQP/2Payl5eG2A7Q3g7FU9GEWXTRiww529zNDGdDKHmtwkzVvgkB7lvIRDd8rCbGuu3sEOusudFrpiwuNABtGYmbz0+cbfLUHZo8EpFsYH5rU7CZjLN4utlE=
  - secure: C5u2ufBJoInILvX0///M4paUg/LBZ3z13K0AfzFTqfITLFnN0BqKg9ySBRhonbXaTDE2r+D2ji0YPLmh+/VC2VQ4rOMyYZL2nlkcqQgHSq00ZJc5K9RWVJKpXksxKnv5Yue6IfSFrUwqlV5UzuO4vB0C5y4LGDpOX9Yyj0fuEXo=
  - secure: kEQAPnFwmk8O+FTOuvx2j67XiSn40DUUNkTI5YGyvDbQImMnrxwJGddcMu9G4j23hCAP4A+DmcnKRjDNTcp1zO6eBJ2G5FglpdPiAaxmavLcuHJx+5SgYITAmRwtmQFnQVMHqEv+yI1HZjZAq8ISlF1JdFnZ2gce4JHi9smWj2E=
language: python
python:
- '2.7'
install: pip install -r test/requirements.txt
before_script:
- gem install --version 0.8.9 faraday --no-ri --no-rdoc
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
