kit:
  name: "Component Tomcat Dev"
  link: https://github.com/qubell-bazaar/component-tomcat-dev
  applications:
    - name: "Load Balancer"
      manifest: https://raw.github.com/qubell-bazaar/component-haproxy/master/component-haproxy.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * CloudServers account;
        * Ports 80 and 1926 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
